[[LAPACK32]]
arch = "aarch64"
git-tree-sha1 = "e507d123c612a257c22d710f0aa675dff859cf1e"
libgfortran_version = "5.0.0"
os = "macos"

    [[LAPACK32.download]]
    sha256 = "20c2e5b7560113d660500b481128303830aa74bc5c35828647d1277f123045ac"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[LAPACK32]]
arch = "aarch64"
git-tree-sha1 = "855b05bee3f7d833a5a6eddca7ff8355b96dfb7a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK32.download]]
    sha256 = "449d9d098fd688c5972ff131d8e7a592593f67f0bda49ac54c4ab140e215cbd8"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[LAPACK32]]
arch = "aarch64"
git-tree-sha1 = "29faf802b3ad9ab2ee282abc30541cc56358e489"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK32.download]]
    sha256 = "3727a5a4f5bc8d9ddc45769d677d45f6c2d78979e89e4ac06b867825e678a7eb"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[LAPACK32]]
arch = "aarch64"
git-tree-sha1 = "ffdf9f02658c603e2b99e91540e2a354ebbfe50f"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[LAPACK32.download]]
    sha256 = "853a524809a5ce53d925dc07f4878ebb8508604b53aa6f9aab1524efdff25de7"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[LAPACK32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "db185832db883ad22db13eb31aaed0eb1f57d49d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK32.download]]
    sha256 = "ed47606d6aab8d6b716d124e0d614f230b52f1265ed9cdce0e2586937f2dca7a"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[LAPACK32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1bff2ab159c5965443446c7c03ea31c624ef6cbb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK32.download]]
    sha256 = "666c38618bcba127e11c9da4872781633a40d513d3adeb4d291711d0a7962c8c"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[LAPACK32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9a4c2f8e9f35875111106446ee72fcf50c3e1574"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK32.download]]
    sha256 = "9d3851fddce14edff9883e28cd0af4cdc255d8aa953290e265a80ede4a77fb7d"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[LAPACK32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6456d08a38c5e3a874d94870813a1a54550bdaf9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK32.download]]
    sha256 = "e6836f4f6ce5c698a8c8bb3fc60c9c19b1faa6cf753116b4323746dde61319d0"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[LAPACK32]]
arch = "i686"
git-tree-sha1 = "b151c30014e2440fbbcebf88a1339336fc22d2e3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK32.download]]
    sha256 = "82c80cff5a716a66d7449b1874ee009f67635a83203620688042ac63a77d957e"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.i686-linux-gnu-libgfortran5.tar.gz"
[[LAPACK32]]
arch = "i686"
git-tree-sha1 = "d68f4181cac7b673be5f7fd65aad1a0d1d6fb4c0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK32.download]]
    sha256 = "73c5debcd88ba640043f9fe0b905f4d77302de7eedb71e9ba601781d89659548"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.i686-linux-musl-libgfortran5.tar.gz"
[[LAPACK32]]
arch = "i686"
git-tree-sha1 = "c86eb3bba2e05c158e70210082eb968ce542b372"
libgfortran_version = "5.0.0"
os = "windows"

    [[LAPACK32.download]]
    sha256 = "8c74c4a90cf40524bb7d49d679e090877195cb5a8cd1b9a89b39b167d7854c90"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[LAPACK32]]
arch = "powerpc64le"
git-tree-sha1 = "c0078e6f25ef4e88e04d6949c231e8d93587342f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK32.download]]
    sha256 = "e87ec94c628ef3548ab7218d84005f5ae2a26e9e0e1f54268e85079fda068349"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[LAPACK32]]
arch = "riscv64"
git-tree-sha1 = "69efe239d2540367ed273e4afb3ed99cde9b56c5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK32.download]]
    sha256 = "8d23fe5f6250be520ea06453155cbb83d4228feae0f0448d1edab16fd54b896b"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.riscv64-linux-gnu-libgfortran5.tar.gz"
[[LAPACK32]]
arch = "x86_64"
git-tree-sha1 = "93e3c74e56f49f57275be16d908854ba5f2bc21c"
libgfortran_version = "5.0.0"
os = "macos"

    [[LAPACK32.download]]
    sha256 = "d23bdffeed913b8ec0fc91e536fda5362e2672d902bd3784ced0c6e5b00465c6"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[LAPACK32]]
arch = "x86_64"
git-tree-sha1 = "d9461a3390c917d11aa6d0fef6be8a2b53c4f8fd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK32.download]]
    sha256 = "82adedde3138d577729886dfd762ff90694a884deac4c3fb8800e503b4ffb78e"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[LAPACK32]]
arch = "x86_64"
git-tree-sha1 = "39cc8c60dd62036598e8b6b072b0a56bec8a9769"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK32.download]]
    sha256 = "ce36ea47eb64517c0c4908fd96668c324a6ced10e29dee5605ddf2ad73b66bc2"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[LAPACK32]]
arch = "x86_64"
git-tree-sha1 = "95408df1d7538fcfb559d569d2577dd1023f1144"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[LAPACK32.download]]
    sha256 = "f5efb816df8c242bca4d74fff0f29a97edcd95983923a03c55de758553e0a7dc"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[LAPACK32]]
arch = "x86_64"
git-tree-sha1 = "e9fa9009d0b20ddf34430a10bdd2ae83224b1b76"
libgfortran_version = "5.0.0"
os = "windows"

    [[LAPACK32.download]]
    sha256 = "c47fa56816bbf248d261fe9e415414f97ce5611fd222915fcb330bc570ec1aaf"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK32_jll.jl/releases/download/LAPACK32-v3.12.1+1/LAPACK32.v3.12.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
